/* eslint-disable */
/**
 * AUTO-GENERATED by `npm run api:sync` in the admin repo (stumarmaspindzeli).
 * Typed references to the public Convex functions. Do not edit by hand.
 */
import { type FunctionReference, anyApi } from "convex/server";
import { type GenericId as Id } from "convex/values";

export const api: PublicApiType = anyApi as unknown as PublicApiType;
export const internal: InternalApiType = anyApi as unknown as InternalApiType;

export type PublicApiType = {
  users: {
    current: FunctionReference<
      "query",
      "public",
      Record<string, never>,
      {
        _creationTime: number;
        _id: Id<"users">;
        email?: string;
        externalId: string;
        imageUrl?: string;
        name: string;
        profileSyncedAt?: number;
      } | null
    >;
    me: FunctionReference<
      "query",
      "public",
      Record<string, never>,
      {
        supervisor: boolean;
        user: {
          _creationTime: number;
          _id: Id<"users">;
          email?: string;
          externalId: string;
          imageUrl?: string;
          name: string;
          profileSyncedAt?: number;
        };
      } | null
    >;
    store: FunctionReference<
      "mutation",
      "public",
      { email?: string; imageUrl?: string; name?: string },
      Id<"users">
    >;
  };
  pushSubscriptions: {
    subscribe: FunctionReference<
      "mutation",
      "public",
      { auth: string; endpoint: string; p256dh: string; userAgent?: string },
      null
    >;
    unsubscribe: FunctionReference<
      "mutation",
      "public",
      { endpoint: string },
      null
    >;
    isSubscribed: FunctionReference<
      "query",
      "public",
      { endpoint: string },
      boolean
    >;
  };
  ai: {
    draftSteps: FunctionReference<
      "action",
      "public",
      {
        hotelId: Id<"hotels">;
        language?: string;
        roughText: string;
        title: string;
      },
      Array<string>
    >;
  };
  catalog: {
    list: FunctionReference<
      "query",
      "public",
      { hotelId: Id<"hotels"> },
      Array<{
        _creationTime: number;
        _id: Id<"catalogItems">;
        allowNote: boolean;
        allowQuantity: boolean;
        archived: boolean;
        departmentId?: Id<"departments">;
        departmentName?: string;
        estimatedMinutes?: number;
        guestDescription?: string;
        guestTitle: string;
        hotelId: Id<"hotels">;
        icon?: string;
        key?: string;
        kind: "request" | "offer" | "info" | "link" | "internal";
        maxQuantity?: number;
        price?: number;
        section:
          | "housekeeping"
          | "dining"
          | "spa"
          | "aquapark"
          | "stay"
          | "hotels"
          | "other";
        sortOrder: number;
        steps: Array<string>;
        title: string;
        url?: string;
        visible: boolean;
      }>
    >;
    create: FunctionReference<
      "mutation",
      "public",
      {
        allowNote: boolean;
        allowQuantity: boolean;
        departmentId?: Id<"departments">;
        estimatedMinutes?: number;
        guestDescription?: string;
        guestTitle: string;
        hotelId: Id<"hotels">;
        icon?: string;
        key?: string;
        kind: "request" | "offer" | "info" | "link" | "internal";
        maxQuantity?: number;
        price?: number;
        section:
          | "housekeeping"
          | "dining"
          | "spa"
          | "aquapark"
          | "stay"
          | "hotels"
          | "other";
        steps: Array<string>;
        title: string;
        url?: string;
        visible?: boolean;
      },
      Id<"catalogItems">
    >;
    update: FunctionReference<
      "mutation",
      "public",
      {
        allowNote?: boolean;
        allowQuantity?: boolean;
        departmentId?: Id<"departments"> | null;
        estimatedMinutes?: number | null;
        guestDescription?: string | null;
        guestTitle?: string;
        icon?: string | null;
        itemId: Id<"catalogItems">;
        key?: string | null;
        kind?: "request" | "offer" | "info" | "link" | "internal";
        maxQuantity?: number | null;
        price?: number | null;
        section?:
          | "housekeeping"
          | "dining"
          | "spa"
          | "aquapark"
          | "stay"
          | "hotels"
          | "other";
        steps?: Array<string>;
        title?: string;
        url?: string | null;
        visible?: boolean;
      },
      null
    >;
    setVisible: FunctionReference<
      "mutation",
      "public",
      { itemId: Id<"catalogItems">; visible: boolean },
      null
    >;
    remove: FunctionReference<
      "mutation",
      "public",
      { itemId: Id<"catalogItems"> },
      null
    >;
    reorder: FunctionReference<
      "mutation",
      "public",
      { hotelId: Id<"hotels">; itemIds: Array<Id<"catalogItems">> },
      null
    >;
    seedDefaults: FunctionReference<
      "mutation",
      "public",
      { hotelId: Id<"hotels"> },
      { inserted: number }
    >;
  };
  departments: {
    list: FunctionReference<
      "query",
      "public",
      { hotelId: Id<"hotels"> },
      Array<{
        _creationTime: number;
        _id: Id<"departments">;
        archived: boolean;
        escalationMinutes: number;
        hotelId: Id<"hotels">;
        icon: string;
        name: string;
        openTaskCount: number;
        sortOrder: number;
      }>
    >;
    create: FunctionReference<
      "mutation",
      "public",
      {
        escalationMinutes: number;
        hotelId: Id<"hotels">;
        icon: string;
        name: string;
      },
      Id<"departments">
    >;
    update: FunctionReference<
      "mutation",
      "public",
      {
        departmentId: Id<"departments">;
        escalationMinutes?: number;
        icon?: string;
        name?: string;
        sortOrder?: number;
      },
      null
    >;
    archive: FunctionReference<
      "mutation",
      "public",
      { departmentId: Id<"departments"> },
      null
    >;
  };
  guest: {
    catalog: {
      list: FunctionReference<
        "query",
        "public",
        { token: string },
        Array<{
          allowNote: boolean;
          allowQuantity: boolean;
          departmentName?: string;
          description?: string;
          icon?: string;
          id: Id<"catalogItems">;
          key?: string;
          kind: "request" | "offer" | "info" | "link" | "internal";
          maxQuantity?: number;
          minutes?: number;
          price?: number;
          section:
            | "housekeeping"
            | "dining"
            | "spa"
            | "aquapark"
            | "stay"
            | "hotels"
            | "other";
          title: string;
          url?: string;
        }>
      >;
    };
    events: {
      track: FunctionReference<
        "mutation",
        "public",
        { kind: "open_app" | "view_feature"; target?: string; token: string },
        null
      >;
    };
    requests: {
      cancel: FunctionReference<
        "mutation",
        "public",
        { key?: string; taskId: Id<"tasks">; token: string },
        null
      >;
      create: FunctionReference<
        "mutation",
        "public",
        {
          detail?: string;
          itemId?: Id<"catalogItems">;
          itemKey?: string;
          key?: string;
          note?: string;
          quantity?: number;
          token: string;
        },
        Id<"tasks">
      >;
      createOrder: FunctionReference<
        "mutation",
        "public",
        {
          key?: string;
          lines: Array<{
            itemId?: Id<"catalogItems">;
            itemKey?: string;
            quantity: number;
          }>;
          note?: string;
          token: string;
        },
        Id<"tasks">
      >;
      list: FunctionReference<
        "query",
        "public",
        { key?: string; token: string },
        Array<{
          acceptedAt?: number;
          createdAt: number;
          departmentName: string;
          detail?: string;
          doneAt?: number;
          id: Id<"tasks">;
          price?: number;
          quantity?: number;
          rating?: number;
          status: "open" | "accepted" | "in_progress" | "done" | "cancelled";
          title: string;
        }>
      >;
      rate: FunctionReference<
        "mutation",
        "public",
        { key?: string; rating: number; taskId: Id<"tasks">; token: string },
        null
      >;
    };
    session: {
      get: FunctionReference<
        "query",
        "public",
        { token: string },
        null | {
          hotel: {
            brandName?: string;
            checkoutTime?: string;
            collection?: string;
            guestLanguages?: Array<string>;
            name: string;
            phone?: string;
          };
          room: { number: string };
          stay: null | {
            checkInAt: number;
            expectedCheckOutAt: number;
            language?: string;
          };
          wifi: null | { network: string; password: string };
        }
      >;
    };
    storefront: {
      bySlug: FunctionReference<
        "query",
        "public",
        { slug: string },
        {
          events: Array<{
            daysOfWeek?: Array<number>;
            id: Id<"resortEvents">;
            place?: string;
            time: string;
            title: string;
          }>;
          hotel: {
            brandName?: string;
            checkoutTime?: string;
            collection?: string;
            guestLanguages?: Array<string>;
            name: string;
            phone?: string;
            slug: string;
            timezone: string;
          };
          items: Array<{
            allowNote: boolean;
            allowQuantity: boolean;
            departmentName?: string;
            description?: string;
            icon?: string;
            id: Id<"catalogItems">;
            key?: string;
            kind: "request" | "offer" | "info" | "link" | "internal";
            maxQuantity?: number;
            minutes?: number;
            price?: number;
            section:
              | "housekeeping"
              | "dining"
              | "spa"
              | "aquapark"
              | "stay"
              | "hotels"
              | "other";
            title: string;
            url?: string;
          }>;
          room: { number: string } | null;
          settings: {
            footerNote?: string;
            heroEyebrow: string;
            heroHighlight: string;
            heroSubtitle: string;
            heroTitle: string;
            heroTitleEnd: string;
          };
          stay: {
            checkInAt: number;
            expectedCheckOutAt: number;
            language?: string;
            pinRequired: boolean;
          } | null;
          tiles: Array<{
            blurb: string;
            body?: string;
            facts?: Array<{ label: string; value: string }>;
            hours?: string;
            howItWorks?: Array<{ body: string; title: string }>;
            icon: string;
            id: Id<"storefrontTiles">;
            inNav: boolean;
            itemKey?: string;
            navLabel?: string;
            options?: Array<string>;
            section?:
              | "housekeeping"
              | "dining"
              | "spa"
              | "aquapark"
              | "stay"
              | "hotels"
              | "other";
            size: "normal" | "wide";
            slots?: Array<string>;
            title: string;
            tone: "light" | "dark";
            type:
              | "requests"
              | "menu"
              | "booking"
              | "ticket"
              | "concierge"
              | "events"
              | "stay"
              | "links"
              | "checkout"
              | "info";
          }>;
          wifi: { network: string; password: string } | null;
        } | null
      >;
      byToken: FunctionReference<
        "query",
        "public",
        { token: string },
        {
          events: Array<{
            daysOfWeek?: Array<number>;
            id: Id<"resortEvents">;
            place?: string;
            time: string;
            title: string;
          }>;
          hotel: {
            brandName?: string;
            checkoutTime?: string;
            collection?: string;
            guestLanguages?: Array<string>;
            name: string;
            phone?: string;
            slug: string;
            timezone: string;
          };
          items: Array<{
            allowNote: boolean;
            allowQuantity: boolean;
            departmentName?: string;
            description?: string;
            icon?: string;
            id: Id<"catalogItems">;
            key?: string;
            kind: "request" | "offer" | "info" | "link" | "internal";
            maxQuantity?: number;
            minutes?: number;
            price?: number;
            section:
              | "housekeeping"
              | "dining"
              | "spa"
              | "aquapark"
              | "stay"
              | "hotels"
              | "other";
            title: string;
            url?: string;
          }>;
          room: { number: string } | null;
          settings: {
            footerNote?: string;
            heroEyebrow: string;
            heroHighlight: string;
            heroSubtitle: string;
            heroTitle: string;
            heroTitleEnd: string;
          };
          stay: {
            checkInAt: number;
            expectedCheckOutAt: number;
            language?: string;
            pinRequired: boolean;
          } | null;
          tiles: Array<{
            blurb: string;
            body?: string;
            facts?: Array<{ label: string; value: string }>;
            hours?: string;
            howItWorks?: Array<{ body: string; title: string }>;
            icon: string;
            id: Id<"storefrontTiles">;
            inNav: boolean;
            itemKey?: string;
            navLabel?: string;
            options?: Array<string>;
            section?:
              | "housekeeping"
              | "dining"
              | "spa"
              | "aquapark"
              | "stay"
              | "hotels"
              | "other";
            size: "normal" | "wide";
            slots?: Array<string>;
            title: string;
            tone: "light" | "dark";
            type:
              | "requests"
              | "menu"
              | "booking"
              | "ticket"
              | "concierge"
              | "events"
              | "stay"
              | "links"
              | "checkout"
              | "info";
          }>;
          wifi: { network: string; password: string } | null;
        } | null
      >;
      directory: FunctionReference<
        "query",
        "public",
        Record<string, never>,
        Array<{ brandName?: string; name: string; slug: string }>
      >;
    };
    pin: {
      unlock: FunctionReference<
        "mutation",
        "public",
        { pin: string; token: string },
        { key: string | null; ok: true } | { message: string; ok: false }
      >;
    };
    ai: {
      clear: FunctionReference<
        "mutation",
        "public",
        { secret: string; threadId: string },
        null
      >;
      messages: FunctionReference<
        "query",
        "public",
        {
          paginationOpts: {
            cursor: string | null;
            endCursor?: string | null;
            id?: number;
            maximumBytesRead?: number;
            maximumRowsRead?: number;
            numItems: number;
          };
          secret: string;
          streamArgs?:
            | { kind: "list"; startOrder?: number }
            | {
                cursors: Array<{ cursor: number; streamId: string }>;
                kind: "deltas";
              };
          threadId: string;
        },
        {
          continueCursor: string;
          isDone: boolean;
          page: Array<any>;
          pageStatus?: "SplitRecommended" | "SplitRequired" | null;
          splitCursor?: string | null;
          streams?:
            | {
                kind: "list";
                messages: Array<{
                  agentName?: string;
                  format?: "UIMessageChunk" | "TextStreamPart";
                  model?: string;
                  order: number;
                  provider?: string;
                  providerOptions?: Record<string, Record<string, any>>;
                  status: "streaming" | "finished" | "aborted";
                  stepOrder: number;
                  streamId: string;
                  userId?: string;
                }>;
              }
            | {
                deltas: Array<{
                  end: number;
                  parts: Array<any>;
                  start: number;
                  streamId: string;
                }>;
                kind: "deltas";
              };
        }
      >;
      send: FunctionReference<
        "mutation",
        "public",
        {
          key?: string;
          prompt: string;
          secret: string;
          threadId: string;
          token?: string;
        },
        null
      >;
      start: FunctionReference<
        "mutation",
        "public",
        { slug?: string; token?: string },
        { secret: string; threadId: string }
      >;
    };
  };
  hotels: {
    create: FunctionReference<
      "mutation",
      "public",
      { defaultLanguage?: string; name: string },
      Id<"hotels">
    >;
    mine: FunctionReference<
      "query",
      "public",
      Record<string, never>,
      Array<{
        departmentIds: Array<Id<"departments">>;
        hotel: {
          _creationTime: number;
          _id: Id<"hotels">;
          address?: string;
          brandName?: string;
          checkoutTime?: string;
          collection?: string;
          defaultLanguage: string;
          guestLanguages?: Array<string>;
          joinCode: string;
          name: string;
          ownerUserId: Id<"users">;
          phone?: string;
          requireGuestPin?: boolean;
          slug: string;
          timezone?: string;
          wifiName?: string;
          wifiPassword?: string;
        };
        membershipId: Id<"memberships">;
        onShift: boolean;
        role: "manager" | "reception" | "staff";
        supervisor: boolean;
      }>
    >;
    get: FunctionReference<
      "query",
      "public",
      { hotelId: Id<"hotels"> },
      {
        _creationTime: number;
        _id: Id<"hotels">;
        address?: string;
        brandName?: string;
        checkoutTime?: string;
        collection?: string;
        defaultLanguage: string;
        guestLanguages?: Array<string>;
        joinCode: string;
        name: string;
        ownerUserId: Id<"users">;
        phone?: string;
        requireGuestPin?: boolean;
        slug: string;
        timezone?: string;
        wifiName?: string;
        wifiPassword?: string;
      } | null
    >;
    update: FunctionReference<
      "mutation",
      "public",
      {
        address?: string;
        brandName?: string;
        checkoutTime?: string;
        collection?: string;
        defaultLanguage?: string;
        guestLanguages?: Array<string>;
        hotelId: Id<"hotels">;
        name?: string;
        phone?: string;
        requireGuestPin?: boolean;
        timezone?: string;
        wifiName?: string;
        wifiPassword?: string;
      },
      null
    >;
    join: FunctionReference<
      "mutation",
      "public",
      { joinCode: string },
      Id<"hotels">
    >;
    regenerateJoinCode: FunctionReference<
      "mutation",
      "public",
      { hotelId: Id<"hotels"> },
      string
    >;
  };
  members: {
    list: FunctionReference<
      "query",
      "public",
      { hotelId: Id<"hotels"> },
      Array<{
        completedTaskCount: number;
        departmentIds: Array<Id<"departments">>;
        email?: string;
        imageUrl?: string;
        membershipId: Id<"memberships">;
        name: string;
        onShift: boolean;
        role: "manager" | "reception" | "staff";
        userId: Id<"users">;
      }>
    >;
    me: FunctionReference<
      "query",
      "public",
      { hotelId: Id<"hotels"> },
      {
        completedTaskCount: number;
        departmentIds: Array<Id<"departments">>;
        email?: string;
        imageUrl?: string;
        membershipId: Id<"memberships">;
        name: string;
        onShift: boolean;
        role: "manager" | "reception" | "staff";
        userId: Id<"users">;
      } | null
    >;
    update: FunctionReference<
      "mutation",
      "public",
      {
        departmentIds?: Array<Id<"departments">>;
        membershipId: Id<"memberships">;
        role?: "manager" | "reception" | "staff";
      },
      null
    >;
    remove: FunctionReference<
      "mutation",
      "public",
      { membershipId: Id<"memberships"> },
      null
    >;
    setOnShift: FunctionReference<
      "mutation",
      "public",
      { hotelId: Id<"hotels">; onShift: boolean },
      null
    >;
  };
  rooms: {
    create: FunctionReference<
      "mutation",
      "public",
      { floor?: string; hotelId: Id<"hotels">; number: string },
      Id<"rooms">
    >;
    createRange: FunctionReference<
      "mutation",
      "public",
      { floor?: string; from: number; hotelId: Id<"hotels">; to: number },
      { created: number; skipped: number }
    >;
    list: FunctionReference<
      "query",
      "public",
      { hotelId: Id<"hotels"> },
      Array<{
        _creationTime: number;
        _id: Id<"rooms">;
        active: boolean;
        currentStay: {
          checkInAt: number;
          expectedCheckOutAt: number;
          guestLabel?: string;
          openTasks: number;
          stayId: Id<"stays">;
        } | null;
        floor?: string;
        number: string;
        token?: string;
      }>
    >;
    remove: FunctionReference<
      "mutation",
      "public",
      { roomId: Id<"rooms"> },
      null
    >;
    rotateToken: FunctionReference<
      "mutation",
      "public",
      { roomId: Id<"rooms"> },
      string
    >;
    update: FunctionReference<
      "mutation",
      "public",
      {
        active?: boolean;
        floor?: string;
        number?: string;
        roomId: Id<"rooms">;
      },
      null
    >;
  };
  stats: {
    overview: FunctionReference<
      "query",
      "public",
      { day: string; hotelId: Id<"hotels"> },
      {
        departmentLoad: Array<{
          avgResponseMin: number | null;
          departmentId: Id<"departments">;
          icon: string;
          name: string;
          open: number;
        }>;
        escalatedOpen: number;
        inHouse: number;
        last7: Array<{
          avgResponseMin: number | null;
          day: string;
          done: number;
          requests: number;
        }>;
        openByStatus: { accepted: number; in_progress: number; open: number };
        roomsTotal: number;
        today: {
          appOpens: number;
          byDepartment: Record<string, number>;
          byItem: Record<string, number>;
          completionCount: number;
          completionMsTotal: number;
          day: string;
          done: number;
          featureViews: Record<string, number>;
          requests: number;
          responseCount: number;
          responseCountByDepartment: Record<string, number>;
          responseMsByDepartment: Record<string, number>;
          responseMsTotal: number;
        };
        topItems: Array<{ count: number; key: string; title: string }>;
      }
    >;
    activity: FunctionReference<
      "query",
      "public",
      { hotelId: Id<"hotels"> },
      Array<{
        at: number;
        kind:
          | "task_created"
          | "task_accepted"
          | "task_in_progress"
          | "task_done"
          | "task_cancelled"
          | "guest_open_app"
          | "guest_view_feature"
          | "guest_rate";
        roomNumber?: string;
        taskId?: Id<"tasks">;
        text: string;
      }>
    >;
  };
  stays: {
    checkIn: FunctionReference<
      "mutation",
      "public",
      {
        adults?: number;
        children?: number;
        expectedCheckOutAt: number;
        guestLabel?: string;
        hotelId: Id<"hotels">;
        language?: string;
        note?: string;
        pmsRef?: string;
        roomId: Id<"rooms">;
      },
      Id<"stays">
    >;
    checkOut: FunctionReference<
      "mutation",
      "public",
      { stayId: Id<"stays"> },
      null
    >;
    extend: FunctionReference<
      "mutation",
      "public",
      { expectedCheckOutAt: number; stayId: Id<"stays"> },
      null
    >;
    get: FunctionReference<
      "query",
      "public",
      { stayId: Id<"stays"> },
      {
        room: { _id: Id<"rooms">; floor?: string; number: string } | null;
        stay: {
          _creationTime: number;
          _id: Id<"stays">;
          adults?: number;
          checkInAt: number;
          checkedOutAt?: number;
          children?: number;
          expectedCheckOutAt: number;
          guestKey?: string;
          guestLabel?: string;
          guestPin?: string;
          hotelId: Id<"hotels">;
          language?: string;
          note?: string;
          pmsRef?: string;
          purgedAt?: number;
          roomId: Id<"rooms">;
          status: "active" | "checked_out";
        };
        tasks: Array<{
          _creationTime: number;
          _id: Id<"tasks">;
          acceptedAt?: number;
          assigneeName?: string;
          assigneeUserId?: Id<"users">;
          cancelledAt?: number;
          createdByUserId?: Id<"users">;
          departmentId: Id<"departments">;
          departmentName: string;
          detail?: string;
          doneAt?: number;
          escalatedAt?: number;
          firstAcceptedAt?: number;
          guestNote?: string;
          hotelId: Id<"hotels">;
          itemId?: Id<"catalogItems">;
          itemKey?: string;
          price?: number;
          priority: "normal" | "high";
          quantity?: number;
          rating?: number;
          roomId?: Id<"rooms">;
          roomNumber?: string;
          source: "guest" | "staff" | "manager";
          startedAt?: number;
          status: "open" | "accepted" | "in_progress" | "done" | "cancelled";
          stayId?: Id<"stays">;
          steps: Array<{
            doneAt?: number;
            doneByUserId?: Id<"users">;
            text: string;
          }>;
          title: string;
        }>;
      } | null
    >;
    listActive: FunctionReference<
      "query",
      "public",
      { hotelId: Id<"hotels"> },
      Array<{
        _creationTime: number;
        _id: Id<"stays">;
        adults?: number;
        checkInAt: number;
        checkedOutAt?: number;
        children?: number;
        expectedCheckOutAt: number;
        guestKey?: string;
        guestLabel?: string;
        guestPin?: string;
        hotelId: Id<"hotels">;
        language?: string;
        note?: string;
        openTasks: number;
        pmsRef?: string;
        purgedAt?: number;
        roomId: Id<"rooms">;
        roomNumber?: string;
        status: "active" | "checked_out";
      }>
    >;
    resetPin: FunctionReference<
      "mutation",
      "public",
      { stayId: Id<"stays"> },
      string
    >;
  };
  tasks: {
    board: FunctionReference<
      "query",
      "public",
      {
        departmentId?: Id<"departments">;
        doneSince: number;
        hotelId: Id<"hotels">;
      },
      {
        accepted: Array<{
          _creationTime: number;
          _id: Id<"tasks">;
          acceptedAt?: number;
          assigneeName?: string;
          assigneeUserId?: Id<"users">;
          cancelledAt?: number;
          createdByUserId?: Id<"users">;
          departmentId: Id<"departments">;
          departmentName: string;
          detail?: string;
          doneAt?: number;
          escalatedAt?: number;
          firstAcceptedAt?: number;
          guestNote?: string;
          hotelId: Id<"hotels">;
          itemId?: Id<"catalogItems">;
          itemKey?: string;
          price?: number;
          priority: "normal" | "high";
          quantity?: number;
          rating?: number;
          roomId?: Id<"rooms">;
          roomNumber?: string;
          source: "guest" | "staff" | "manager";
          startedAt?: number;
          status: "open" | "accepted" | "in_progress" | "done" | "cancelled";
          stayId?: Id<"stays">;
          steps: Array<{
            doneAt?: number;
            doneByUserId?: Id<"users">;
            text: string;
          }>;
          title: string;
        }>;
        done: Array<{
          _creationTime: number;
          _id: Id<"tasks">;
          acceptedAt?: number;
          assigneeName?: string;
          assigneeUserId?: Id<"users">;
          cancelledAt?: number;
          createdByUserId?: Id<"users">;
          departmentId: Id<"departments">;
          departmentName: string;
          detail?: string;
          doneAt?: number;
          escalatedAt?: number;
          firstAcceptedAt?: number;
          guestNote?: string;
          hotelId: Id<"hotels">;
          itemId?: Id<"catalogItems">;
          itemKey?: string;
          price?: number;
          priority: "normal" | "high";
          quantity?: number;
          rating?: number;
          roomId?: Id<"rooms">;
          roomNumber?: string;
          source: "guest" | "staff" | "manager";
          startedAt?: number;
          status: "open" | "accepted" | "in_progress" | "done" | "cancelled";
          stayId?: Id<"stays">;
          steps: Array<{
            doneAt?: number;
            doneByUserId?: Id<"users">;
            text: string;
          }>;
          title: string;
        }>;
        in_progress: Array<{
          _creationTime: number;
          _id: Id<"tasks">;
          acceptedAt?: number;
          assigneeName?: string;
          assigneeUserId?: Id<"users">;
          cancelledAt?: number;
          createdByUserId?: Id<"users">;
          departmentId: Id<"departments">;
          departmentName: string;
          detail?: string;
          doneAt?: number;
          escalatedAt?: number;
          firstAcceptedAt?: number;
          guestNote?: string;
          hotelId: Id<"hotels">;
          itemId?: Id<"catalogItems">;
          itemKey?: string;
          price?: number;
          priority: "normal" | "high";
          quantity?: number;
          rating?: number;
          roomId?: Id<"rooms">;
          roomNumber?: string;
          source: "guest" | "staff" | "manager";
          startedAt?: number;
          status: "open" | "accepted" | "in_progress" | "done" | "cancelled";
          stayId?: Id<"stays">;
          steps: Array<{
            doneAt?: number;
            doneByUserId?: Id<"users">;
            text: string;
          }>;
          title: string;
        }>;
        open: Array<{
          _creationTime: number;
          _id: Id<"tasks">;
          acceptedAt?: number;
          assigneeName?: string;
          assigneeUserId?: Id<"users">;
          cancelledAt?: number;
          createdByUserId?: Id<"users">;
          departmentId: Id<"departments">;
          departmentName: string;
          detail?: string;
          doneAt?: number;
          escalatedAt?: number;
          firstAcceptedAt?: number;
          guestNote?: string;
          hotelId: Id<"hotels">;
          itemId?: Id<"catalogItems">;
          itemKey?: string;
          price?: number;
          priority: "normal" | "high";
          quantity?: number;
          rating?: number;
          roomId?: Id<"rooms">;
          roomNumber?: string;
          source: "guest" | "staff" | "manager";
          startedAt?: number;
          status: "open" | "accepted" | "in_progress" | "done" | "cancelled";
          stayId?: Id<"stays">;
          steps: Array<{
            doneAt?: number;
            doneByUserId?: Id<"users">;
            text: string;
          }>;
          title: string;
        }>;
      }
    >;
    myQueue: FunctionReference<
      "query",
      "public",
      { hotelId: Id<"hotels"> },
      Array<{
        _creationTime: number;
        _id: Id<"tasks">;
        acceptedAt?: number;
        assigneeName?: string;
        assigneeUserId?: Id<"users">;
        cancelledAt?: number;
        createdByUserId?: Id<"users">;
        departmentId: Id<"departments">;
        departmentName: string;
        detail?: string;
        doneAt?: number;
        escalatedAt?: number;
        firstAcceptedAt?: number;
        guestNote?: string;
        hotelId: Id<"hotels">;
        itemId?: Id<"catalogItems">;
        itemKey?: string;
        price?: number;
        priority: "normal" | "high";
        quantity?: number;
        rating?: number;
        roomId?: Id<"rooms">;
        roomNumber?: string;
        source: "guest" | "staff" | "manager";
        startedAt?: number;
        status: "open" | "accepted" | "in_progress" | "done" | "cancelled";
        stayId?: Id<"stays">;
        steps: Array<{
          doneAt?: number;
          doneByUserId?: Id<"users">;
          text: string;
        }>;
        title: string;
      }>
    >;
    get: FunctionReference<
      "query",
      "public",
      { taskId: string },
      {
        _creationTime: number;
        _id: Id<"tasks">;
        acceptedAt?: number;
        assigneeName?: string;
        assigneeUserId?: Id<"users">;
        cancelledAt?: number;
        createdByUserId?: Id<"users">;
        departmentId: Id<"departments">;
        departmentName: string;
        detail?: string;
        doneAt?: number;
        escalatedAt?: number;
        estimatedMinutes?: number;
        firstAcceptedAt?: number;
        guestNote?: string;
        hotelId: Id<"hotels">;
        itemId?: Id<"catalogItems">;
        itemKey?: string;
        price?: number;
        priority: "normal" | "high";
        quantity?: number;
        rating?: number;
        roomId?: Id<"rooms">;
        roomNumber?: string;
        source: "guest" | "staff" | "manager";
        startedAt?: number;
        status: "open" | "accepted" | "in_progress" | "done" | "cancelled";
        stay: {
          expectedCheckOutAt: number;
          guestLabel?: string;
          language?: string;
          status: "active" | "checked_out";
          stayId: Id<"stays">;
        } | null;
        stayId?: Id<"stays">;
        steps: Array<{
          doneAt?: number;
          doneByUserId?: Id<"users">;
          text: string;
        }>;
        title: string;
      } | null
    >;
    create: FunctionReference<
      "mutation",
      "public",
      {
        departmentId?: Id<"departments">;
        detail?: string;
        hotelId: Id<"hotels">;
        itemId?: Id<"catalogItems">;
        priority?: "normal" | "high";
        quantity?: number;
        roomId?: Id<"rooms">;
        title?: string;
      },
      Id<"tasks">
    >;
    accept: FunctionReference<
      "mutation",
      "public",
      { taskId: Id<"tasks"> },
      null
    >;
    start: FunctionReference<
      "mutation",
      "public",
      { taskId: Id<"tasks"> },
      null
    >;
    toggleStep: FunctionReference<
      "mutation",
      "public",
      { index: number; taskId: Id<"tasks"> },
      null
    >;
    complete: FunctionReference<
      "mutation",
      "public",
      { taskId: Id<"tasks"> },
      null
    >;
    release: FunctionReference<
      "mutation",
      "public",
      { taskId: Id<"tasks"> },
      null
    >;
    cancel: FunctionReference<
      "mutation",
      "public",
      { taskId: Id<"tasks"> },
      null
    >;
    assign: FunctionReference<
      "mutation",
      "public",
      { taskId: Id<"tasks">; userId: Id<"users"> },
      null
    >;
  };
  routines: {
    list: FunctionReference<
      "query",
      "public",
      { hotelId: Id<"hotels"> },
      Array<{
        _creationTime: number;
        _id: Id<"routines">;
        active: boolean;
        daysOfWeek: Array<number>;
        departmentId: Id<"departments">;
        departmentName: string;
        hotelId: Id<"hotels">;
        itemId: Id<"catalogItems">;
        itemTitle: string;
        lastRunDay?: string;
        scope: "once" | "each_occupied_room" | "each_room";
        time: string;
        title?: string;
      }>
    >;
    create: FunctionReference<
      "mutation",
      "public",
      {
        active?: boolean;
        daysOfWeek: Array<number>;
        departmentId?: Id<"departments">;
        hotelId: Id<"hotels">;
        itemId: Id<"catalogItems">;
        scope: "once" | "each_occupied_room" | "each_room";
        time: string;
        title?: string;
      },
      Id<"routines">
    >;
    update: FunctionReference<
      "mutation",
      "public",
      {
        active?: boolean;
        daysOfWeek?: Array<number>;
        departmentId?: Id<"departments">;
        itemId?: Id<"catalogItems">;
        routineId: Id<"routines">;
        scope?: "once" | "each_occupied_room" | "each_room";
        time?: string;
        title?: string | null;
      },
      null
    >;
    remove: FunctionReference<
      "mutation",
      "public",
      { routineId: Id<"routines"> },
      null
    >;
  };
  storefront: {
    get: FunctionReference<
      "query",
      "public",
      { hotelId: Id<"hotels"> },
      {
        settings: {
          footerNote?: string;
          heroEyebrow: string;
          heroHighlight: string;
          heroSubtitle: string;
          heroTitle: string;
          heroTitleEnd: string;
        };
        tiles: Array<{
          _creationTime: number;
          _id: Id<"storefrontTiles">;
          blurb: string;
          body?: string;
          facts?: Array<{ label: string; value: string }>;
          hotelId: Id<"hotels">;
          hours?: string;
          howItWorks?: Array<{ body: string; title: string }>;
          icon: string;
          inNav: boolean;
          itemKey?: string;
          navLabel?: string;
          options?: Array<string>;
          section?:
            | "housekeeping"
            | "dining"
            | "spa"
            | "aquapark"
            | "stay"
            | "hotels"
            | "other";
          size: "normal" | "wide";
          slots?: Array<string>;
          sortOrder: number;
          title: string;
          tone: "light" | "dark";
          type:
            | "requests"
            | "menu"
            | "booking"
            | "ticket"
            | "concierge"
            | "events"
            | "stay"
            | "links"
            | "checkout"
            | "info";
          visible: boolean;
        }>;
      }
    >;
    updateSettings: FunctionReference<
      "mutation",
      "public",
      {
        footerNote?: string;
        heroEyebrow?: string;
        heroHighlight?: string;
        heroSubtitle?: string;
        heroTitle?: string;
        heroTitleEnd?: string;
        hotelId: Id<"hotels">;
      },
      null
    >;
    createTile: FunctionReference<
      "mutation",
      "public",
      {
        blurb: string;
        body?: string;
        facts?: Array<{ label: string; value: string }>;
        hotelId: Id<"hotels">;
        hours?: string;
        howItWorks?: Array<{ body: string; title: string }>;
        icon: string;
        inNav?: boolean;
        itemKey?: string;
        navLabel?: string;
        options?: Array<string>;
        section?:
          | "housekeeping"
          | "dining"
          | "spa"
          | "aquapark"
          | "stay"
          | "hotels"
          | "other";
        size?: "normal" | "wide";
        slots?: Array<string>;
        title: string;
        tone?: "light" | "dark";
        type:
          | "requests"
          | "menu"
          | "booking"
          | "ticket"
          | "concierge"
          | "events"
          | "stay"
          | "links"
          | "checkout"
          | "info";
        visible?: boolean;
      },
      Id<"storefrontTiles">
    >;
    updateTile: FunctionReference<
      "mutation",
      "public",
      {
        blurb?: string;
        body?: string | null;
        facts?: Array<{ label: string; value: string }> | null;
        hours?: string | null;
        howItWorks?: Array<{ body: string; title: string }> | null;
        icon?: string;
        inNav?: boolean;
        itemKey?: string | null;
        navLabel?: string | null;
        options?: Array<string> | null;
        section?:
          | "housekeeping"
          | "dining"
          | "spa"
          | "aquapark"
          | "stay"
          | "hotels"
          | "other"
          | null;
        size?: "normal" | "wide";
        slots?: Array<string> | null;
        tileId: Id<"storefrontTiles">;
        title?: string;
        tone?: "light" | "dark";
        type?:
          | "requests"
          | "menu"
          | "booking"
          | "ticket"
          | "concierge"
          | "events"
          | "stay"
          | "links"
          | "checkout"
          | "info";
        visible?: boolean;
      },
      null
    >;
    removeTile: FunctionReference<
      "mutation",
      "public",
      { tileId: Id<"storefrontTiles"> },
      null
    >;
    reorderTiles: FunctionReference<
      "mutation",
      "public",
      { hotelId: Id<"hotels">; tileIds: Array<Id<"storefrontTiles">> },
      null
    >;
    seedDefaults: FunctionReference<
      "mutation",
      "public",
      { hotelId: Id<"hotels"> },
      {
        eventsInserted: number;
        itemsInserted: number;
        settingsCreated: boolean;
        tilesInserted: number;
      }
    >;
  };
  resortEvents: {
    list: FunctionReference<
      "query",
      "public",
      { hotelId: Id<"hotels"> },
      Array<{
        _creationTime: number;
        _id: Id<"resortEvents">;
        daysOfWeek?: Array<number>;
        hotelId: Id<"hotels">;
        place?: string;
        sortOrder: number;
        time: string;
        title: string;
        visible: boolean;
      }>
    >;
    create: FunctionReference<
      "mutation",
      "public",
      {
        daysOfWeek?: Array<number>;
        hotelId: Id<"hotels">;
        place?: string;
        time: string;
        title: string;
        visible?: boolean;
      },
      Id<"resortEvents">
    >;
    update: FunctionReference<
      "mutation",
      "public",
      {
        daysOfWeek?: Array<number> | null;
        eventId: Id<"resortEvents">;
        place?: string | null;
        sortOrder?: number;
        time?: string;
        title?: string;
        visible?: boolean;
      },
      null
    >;
    remove: FunctionReference<
      "mutation",
      "public",
      { eventId: Id<"resortEvents"> },
      null
    >;
  };
  invitations: {
    list: FunctionReference<
      "query",
      "public",
      { hotelId: Id<"hotels"> },
      Array<{
        _creationTime: number;
        _id: Id<"invitations">;
        departmentIds: Array<Id<"departments">>;
        email: string;
        error?: string;
        inviteUrl?: string;
        role: "manager" | "reception" | "staff";
        status: "pending" | "accepted" | "revoked" | "failed";
      }>
    >;
    create: FunctionReference<
      "mutation",
      "public",
      {
        departmentIds: Array<Id<"departments">>;
        email: string;
        hotelId: Id<"hotels">;
        role: "manager" | "reception" | "staff";
      },
      Id<"invitations">
    >;
    revoke: FunctionReference<
      "mutation",
      "public",
      { invitationId: Id<"invitations"> },
      null
    >;
    resend: FunctionReference<
      "mutation",
      "public",
      { invitationId: Id<"invitations"> },
      null
    >;
  };
  platform: {
    hotels: FunctionReference<
      "query",
      "public",
      Record<string, never>,
      Array<{
        hotel: {
          _creationTime: number;
          _id: Id<"hotels">;
          address?: string;
          brandName?: string;
          checkoutTime?: string;
          collection?: string;
          defaultLanguage: string;
          guestLanguages?: Array<string>;
          joinCode: string;
          name: string;
          ownerUserId: Id<"users">;
          phone?: string;
          requireGuestPin?: boolean;
          slug: string;
          timezone?: string;
          wifiName?: string;
          wifiPassword?: string;
        };
        inHouse: number;
        memberCount: number;
        roomCount: number;
      }>
    >;
    users: FunctionReference<
      "query",
      "public",
      Record<string, never>,
      Array<{
        memberships: Array<{
          hotelId: Id<"hotels">;
          hotelName: string;
          role: "manager" | "reception" | "staff";
        }>;
        supervisor: boolean;
        user: {
          _creationTime: number;
          _id: Id<"users">;
          email?: string;
          externalId: string;
          imageUrl?: string;
          name: string;
          profileSyncedAt?: number;
        };
      }>
    >;
  };
};
export type InternalApiType = {};
